### ISSUE TITLE
as_dict() got an unexpected keyword argument 'relationships'

### ISSUE THREAD

**Issue by jbrieuclp** [PnX-SI/Utils-Flask-SQLAlchemy#1]
Le fait d'avoir `relationships=relationships` fait planter python.
Par contre ça ça marche : `x.as_dict(recursif, relationships)`
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/8d864908914b626b315110db46073b8a257e1244/src/utils_flask_sqla/serializers.py#L107

Au passage il ne devrait pas y avoir les relationships ici aussi ? 
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/6fbf639f38df2111a8cd22d59bdf88ad39c3d2c9/src/utils_flask_sqla/serializers.py#L111

**Comment by TheoLechemia** [comment]
C'est lié au sous-module d'authentification qui réimplémente la méthode "as_dict" sur un modèle.
Il faut passer sur la branche develop du sous module.
Et oui OK pour la 2eme proposition

**Comment by bouttier** [comment]
À priori cette issue est obsolète suite aux évolutions du module.
