### ISSUE TITLE
total_filtered non cohérente

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/Utils-Flask-SQLAlchemy#40]
Sur une instance GeoNature 2.12.3 avec le module d'export 1.5.3 et Utils-Flask-SQLAlchemy 0.3.5, la valeur total_filtered d'un export correspond à la valeur du limit et non au nombre total de données filtrées. cf. la capture suivante ou l'on devrait avoir plus de 500000 données dans le `total_filtered`:

![Screenshot 2023-08-29 at 17-07-28 https __geonature lpo-aura org](https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/assets/22891423/b95085d4-ca66-4a75-8fe4-f27cfa8112e9)

En effet, pour exemple, si l'on fait un count sur une sous-requête contenant un limit, bien on obtient le nombre de résultat 'limité':

```sql
WITH t1 AS (SELECT * FROM gn_synthese.synthese LIMIT 1000 OFFSET 0)
SELECT count(*)
FROM t1;
```
Cela vient a priori de l'éclatement de la fonction `query` de la classe `GenericQuery` en deux fonctions `query` et `raw_query`.

`raw_query`, on applique le limit :
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/bb84968353982951fd24d47e815a104df7322521/src/utils_flask_sqla/generic.py#L254-L255

`query` on compte le nombre de données AVEC le limit :
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/bb84968353982951fd24d47e815a104df7322521/src/utils_flask_sqla/generic.py#L266-L267

En tentant de reproduire sur l'instance de démo, le pb est autre, la valeur limit n'est pas utilisée... le bloc items renvoie TOUS les résultats de la synthese. Il serait intéressant de vérifier la version de  Utils-Flask-SQLAlchemy sur l'instance de démo. j'ai pu constater que la montée en version de Utils-Flask-SQLAlchemy ne s'est pas faite lors de la montée en version du module d'export.

**Comment by camillemonchicourt** [comment]
Sur le serveur de DEMO, le module Exports est actuellement en 1.5.0.

**Comment by cen-cgeier** [comment]
Bonjour à tous,
Je me permets ce post car j'ai un questionnement à propos des dernières modifications apportées.

Le LIMIT est ajouté à `q` `if self.limit != -1` dans la fonction `raw_query`. 
Il est en revanche systématiquement envoyé à la requête `q` à la ligne 273.
https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/29908bfac80a5cf9dc6878fa5ee60e173c3c6d6d/src/utils_flask_sqla/generic.py#L270-L273
N'est-ce pas redondant ou ne doit-il pas y avoir `if self.limit != -1` en amont de la ligne ligne 273?
Il semble que l'envoie systématique du LIMIT à la ligne 273 soit problématique lorsque `limit=-1` (https://github.com/PnX-SI/gn_module_ZH/pull/42)

**Comment by TheoLechemia** [comment]
Salut,
Je pense qu'il faut bannir l'utilisation du -1 qui peut potentiellement dangereuse et peut faire tomber un serveur.
Est-ce qu'il y a vraiment des cas d'usage ?

**Comment by cen-cgeier** [comment]
Celui que je connais est ici
https://github.com/PnX-SI/gn_module_ZH/blob/70a8af29417c5c498a5f19ce5c71d35587a8db33/backend/gn_module_zh/blueprint.py#L814-L822
