### ISSUE TITLE
proprietés hybride dans as_dict

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/Utils-Flask-SQLAlchemy#8]
Dans sqlalchemy on peut définir des propriétés hybride
[lien](https://docs.sqlalchemy.org/en/13/orm/extensions/hybrid.html)

Je me demandais si c'était possible que as_dict puisse traiter aussi les propriété hybrides et comment faire pour les traiter?

**Comment by bouttier** [comment]
C’est désormais supporté et même testé ici : https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/master/src/utils_flask_sqla/tests/test_serializers.py#L570
